version: "3.9"
services:
    # frontend:
    #   build: ./frontend
    #   ports:
    #     - "5000:5000"
    #   links:
    #     - backend
    backend:
      image: "davalejo/flask-api:latest"
      ports: 
        - "5000:5000"
